# Generated by Django 4.0.3 on 2022-08-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_userinfo_liked_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='liked_article',
            field=models.ManyToManyField(blank=True, to='blog.article', verbose_name='喜欢的文章'),
        ),
    ]
